swagger: '2.0'
info:
  version: '1.0.0'
  title: Multi-container - (NOGUEIRA)
  description: Carbono paas module's API that exposes multi-container funcionality (Eg. Docker)
  contact:
    name: Carbono team
    email: team@carbono.io
    url: http://carbono.io
host: localhost:3000
basePath: /nog
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /machines:
    post:
      description: Instanciate a new machine. The machine creation will be performed in backgroud
      operationId: createMachine
      produces:
        - application/json
      parameters:
        - name: machineDetails
          in: body
          description: Details of machine to be instanciated
          required: true
          schema:
            $ref: '#/definitions/newMachineMessage'
      responses:
        '201':
          description: machine creation confirmed
          schema:
            $ref: '#/definitions/newMachineResponse'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description:  Machine not created
          schema:
            $ref: '#/definitions/errorMessage'
        default:
          description:  Unexpected Error
  /machines/{token}:
    get:
      description: Returns a machine creation current status based on a token
      operationId: getMachineCreationStatus
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          description: Token received as response of create
          required: true
          type: string
      responses:
        '201':
          description: machine creation status response
          schema:
            $ref: '#/definitions/machineStatusMessage'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description:  Not Found
          schema:
            $ref: '#/definitions/errorMessage'
        default:
          description:  Unexpected Error
  /tokens:
    post:
      description: Save a token relative to a new machine criation request.
      operationId: saveToken
      produces:
        - application/json
      parameters:
        - name: tokenInfo
          in: body
          description: Token information to store
          required: true
          schema:
            $ref: '#/definitions/tokenMessage'
      responses:
        '200':
          description: token saved sucessfull
          schema:
            $ref: '#/definitions/tokenResponse'
        '400':
          description:  Token could not be saved
          schema:
            $ref: '#/definitions/errorMessage'
        default:
          description:  Unexpected Error
definitions:
  newMachineMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies requested data
          items:
            type: array
            items:
              $ref: '#/definitions/machine'
  newMachineResponse:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
        properties:
          id:
            type: string
            description: represent the token confirming that machine creation will be performed
            default: TOKEN-0001
  machine:
    required:
      - imageName
      - route
    properties:
      imageName:
        type: string
      route:
        type: string
      environment:
        type: string
        description: accepts DEV / HML / PRD
  machineStatus:
    required:
      - status
    properties:
      status:
        type: string
        description: accepts PENDING / OK / FAIL
        default: OK
  machineStatusMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies requested data
          items:
            type: array
            description: An array of data items
            items:
              $ref: '#/definitions/machineStatus'
  tokenMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id containing token value
  tokenResponse:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
        properties:
          id:
            type: string
            description: represent the token confirming that machine creation will be performed
            default: TOKEN-0001
  errorMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the error message
      apiVersion:
        type: string
        description: The version of the api
      error:
        required:
          - code
          - message
        properties:
          code:
            type: integer
            format: int64
            description: The error code (i.e. 400, 404)
          message:
            type: string
            description: The error message