swagger: "2.0"
info:
  description: |
    This API describes the Carbono Authentication Server operations that are unrelated with the OAuth2 flow.
  version: "1.0.0"
  title: Carbono Auth
basePath: /carbono-auth
schemes:
  - http
paths:
  /validate:
    post:
      description: |
        Verify if the given token is valid. It returns a user profile related to the token.
      produces:
        - application/json
      parameters:
        - name: token
          in: body
          description: User's token
          required: true
          schema:
            $ref: '#/definitions/requestUserMessage'
      responses:
        '200':
          description: User retrieved
          schema:
            $ref: '#/definitions/responseUserMessage'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/errorMessage'
        '400':
          description: Malformed request
          schema:
            $ref: '#/definitions/errorMessage'

definitions:
  userInfo:
    required:
      - code
      - name
      - email
    properties:
      code:
        type: string
      name:
        type: string
      email:
        type: string

  requestUserMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the  message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                token:
                  type: string

  responseUserMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the  message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                userInfo:
                  type: object
                  $ref: '#/definitions/userInfo'
  errorMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the error message
      apiVersion:
        type: string
        description: The version of the api
      error:
        required:
          - code
          - message
        properties:
          code:
            type: integer
            format: int64
            description: The error code (i.e. 400, 404)
          message:
            type: string
            description: The error message
