swagger: "2.0"
info:
  description: |
    This API describes the Carbono Authentication Server operations that are unrelated with the OAuth2 flow.
  version: "1.0.0"
  title: Carbono Auth
basePath: /carbono-auth
schemes:
  - http
paths:
  /validate:
    post:
      description: |
        Verify if the given token is valid. It returns a user profile related to the token.
      produces:
        - application/json
      parameters:
        - name: token
          in: body
          description: User's token
          required: true
          schema:
            $ref: '#/definitions/requestUserMessage'
      responses:
        '200':
          description: User retrieved
          schema:
            $ref: '#/definitions/responseUserMessage'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/errorMessage'
        '400':
          description: Malformed request
          schema:
            $ref: '#/definitions/errorMessage'

definitions:
  userInfo:
    properties:
      provider:
        description: Provider with which the user authenticated
        type: string
      id:
        description: Unique identifier for the user, as generated by the service provider.
        type: string
      displayName:
        description: The name of this user, suitable for display.
        type: string
      name:
        type: object
        properties:
          familyName:
            description: The family name of this user, or "last name" in most Western languages.
            type: string
          givenName:
            description: The given name of this user, or "first name" in most Western languages.
            type: string
          middleName:
            description: The middle name of this user.
            type: string
      emails:
        type: array
        items:
          properties:
            value:
              description: The actual email address.
              type: string
            type:
              description: The type of email address (home, work, etc.).
              type: string
      photos:
        type: array
        items:
          properties:
            value:
              description: The URL of the image.
              type: string

  requestUserMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the  message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                token:
                  type: string

  responseUserMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the  message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                userInfo:
                  type: object
                  $ref: '#/definitions/userInfo'
  errorMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the error message
      apiVersion:
        type: string
        description: The version of the api
      error:
        required:
          - code
          - message
        properties:
          code:
            type: integer
            format: int64
            description: The error code (i.e. 400, 404)
          message:
            type: string
            description: The error message
