swagger: '2.0'
info:
  version: '1.0.0'
  title: PaaS - (IPE)
  description: Carbono paas module's API that exposes deploy machine functionality
  contact:
    name: Carbono team
    email: team@carbono.io
    url: http://carbono.io
host: localhost:3000
basePath: /paas
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /machines:
    post:
      description: Instanciate a new machine. The machine creation will be performed in backgroud
      operationId: createMachine
      produces:
        - application/json
      parameters:
        - name: machineDetails
          in: body
          description: DEtails of machine to be instanciated
          required: true
          schema:
            $ref: '#/definitions/newMachineMessage'
      responses:
        '200':
          description: machine creation requested
          schema:
            $ref: '#/definitions/newMachineResponse'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
  /machines/{token}:
    get:
      description: Returns a machine creation current status based on a token
      operationId: getMachineCreationStatus
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          description: Token received as response of create
          required: true
          type: string
      responses:
        '200':
          description: machine creation status response
          schema:
            $ref: '#/definitions/machineStatusMessage'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description:  Not Found
          schema:
            $ref: '#/definitions/errorMessage'
definitions:
  newMachineMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                machine:
                  type: object
                  required:
                    - component
                    - route
                  $ref: '#/definitions/machine'
  newMachineResponse:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
        properties:
          id:
            type: string
            description: represent the token confirming that machine creation will be performed
            default: TOKEN-0001
          items:
            type: array
            description: An array of data items
            items:
              properties:
                machine:
                  type: object
                  required:
                    - component
                    - route
                  $ref: '#/definitions/machine'
  machine:
    properties:
      component:
        type: string
      route:
        type: string
      environment:
        type: string
        description: accepts DEV / HML / PRD
  machineStatus:
    properties:
      status:
        type: string
        description: accepts PENDING / OK / FAIL
        default: OK
  machineStatusMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                machineStatus:
                  type: object
                  required:
                    - status
                  $ref: '#/definitions/machineStatus'
  errorMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the error message
      apiVersion:
        type: string
        description: The version of the api
      error:
        required:
          - code
          - message
        properties:
          code:
            type: integer
            format: int64
            description: The error code (i.e. 400, 404)
          message:
            type: string
            description: The error message