swagger: '2.0'
info:
  version: '1.0.0'
  title: BRL - Account Manager
  description: Account Manager module's API that exposes account and project functionality
  contact:
    name: Carbono team
    email: team@carbono.io
    url: http://carbono.io
host: localhost:3000
basePath: /account-manager
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /profiles:
    post:
      description: Creates a new profile.
      operationId: createProfile
      produces:
        - application/json
      parameters:
        - name: profile
          in: body
          description: Profile to create
          required: true
          schema:
            $ref: '#/definitions/newProfileMessage'
      responses:
        '200':
          description: profile created
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
  /profiles/{code}:
    get:
      description: Returns an profile user based on a ID
      operationId: findProfileByCode
      produces:
        - application/json
      parameters:
        - name: code
          in: path
          description: Profile code
          required: true
          type: string
      responses:
        '200':
          description: profile response
          schema:
            $ref: '#/definitions/profileMessage'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description:  Not Found
          schema:
            $ref: '#/definitions/errorMessage'
  /login:
    post:
      description: Verifies if the credentials are valid.
      operationId: authenticateProfile
      produces:
        - application/json
      parameters:
        - name: credentials
          in: body
          description: Credentials to be validated (email and password)
          required: true
          schema:
            $ref: '#/definitions/credentialsMessage'
      responses:
        '200':
          description: Confirmed credentials
        '400':
          description: Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description: Invalid credentials
          schema:
            $ref: '#/definitions/errorMessage'
  /userInfo:
    post:
      description: Returns all user informations that will be available at oauth.
      operationId: getUserInfo
      produces:
        - application/json
      parameters:
        - name: email
          in: body
          description: User's email
          required: true
          schema:
            $ref: '#/definitions/userEmailMessage'
      responses:
        '200':
          description: User informations.
          schema:
            $ref: '#/definitions/userInfoMessage'
        '400':
          description:  Malformed request
          schema:
            $ref: '#/definitions/errorMessage'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/errorMessage'

definitions:
  newProfileMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the  message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                profile:
                  type: object
                  required:
                    - email
                    - password
                  $ref: '#/definitions/profile'
  profile:
    properties:
      code:
        type: string
      name:
        type: string
      email:
        type: string
      password:
        type: string
  profileMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                profile:
                  type: object
                  required:
                    - code
                    - email
                    - password
                  $ref: '#/definitions/profile'
  credentialsMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
  userInfoMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              properties:
                code:
                  type: string
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
  userEmailMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the message
      apiVersion:
        type: string
        description: The version of the api
      data:
        required:
          - id
          - items
        properties:
          id:
            type: string
            description: Id that unique identifies the requested data
          items:
            type: array
            description: An array of data items
            items:
              required:
                - email
              properties:
                email:
                  type: string
  errorMessage:
    properties:
      id:
        type: string
        description: Id that unique identifies the error message
      apiVersion:
        type: string
        description: The version of the api
      error:
        required:
          - code
          - message
        properties:
          code:
            type: integer
            format: int64
            description: The error code (i.e. 400, 404)
          message:
            type: string
            description: The error message
